version: '3.3'

services:
  donkeycar:
    build: .
    ports:
      - "5000:5000"
    image: mdlopezme/donkeycar:staging
    # network_mode: "host"
    # privileged: true
    # stdin_open: true
    # tty: true
    container_name: donkey_trainer
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]